### ISSUE TITLE
error compile softethervpn

### ISSUE THREAD

**Issue by Borisich76** [Stanback/alpine-softethervpn#1]
Hello. Encountered a problem during assembly, please tell me what could be the problem? Also had to add "libsodium-dev" and change the system to latest.
`Status: Downloaded newer image for alpine:latest
 ---> 28f6e2705743
Step 2/10 : WORKDIR /usr/src
 ---> Running in a4a5a40b9b9c
Removing intermediate container a4a5a40b9b9c
 ---> 5e77f5913996
Step 3/10 : RUN apk add --no-cache       binutils       build-base       readline-dev                      openssl-dev       ncurses-dev       libsodium-dev       git       cmake       gnu-libico               nv       zlib-dev     && git clone --recurse-submodules https://github.com/SoftEtherVPN/So               ftEtherVPN.git     && cd SoftEtherVPN     && ./configure     && make -C tmp     && make -C                tmp install     && tar -czf /artifacts.tar.gz /usr/local
 ---> Running in c05a47791170
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/48) Installing libgcc (10.2.1_pre1-r3)
(2/48) Installing libstdc++ (10.2.1_pre1-r3)
(3/48) Installing binutils (2.35.1-r1)
(4/48) Installing libmagic (5.39-r0)
(5/48) Installing file (5.39-r0)
(6/48) Installing libgomp (10.2.1_pre1-r3)
(7/48) Installing libatomic (10.2.1_pre1-r3)
(8/48) Installing libgphobos (10.2.1_pre1-r3)
(9/48) Installing gmp (6.2.1-r0)
(10/48) Installing isl22 (0.22-r0)
(11/48) Installing mpfr4 (4.1.0-r0)
(12/48) Installing mpc1 (1.2.0-r0)
(13/48) Installing gcc (10.2.1_pre1-r3)
(14/48) Installing musl-dev (1.2.2-r0)
(15/48) Installing libc-dev (0.7.2-r3)
(16/48) Installing g++ (10.2.1_pre1-r3)
(17/48) Installing make (4.3-r0)
(18/48) Installing fortify-headers (1.1-r0)
(19/48) Installing patch (2.7.6-r6)
(20/48) Installing build-base (0.5-r2)
(21/48) Installing libacl (2.2.53-r0)
(22/48) Installing libbz2 (1.0.8-r1)
(23/48) Installing expat (2.2.10-r1)
(24/48) Installing lz4-libs (1.9.2-r0)
(25/48) Installing xz-libs (5.2.5-r0)
(26/48) Installing zstd-libs (1.4.5-r3)
(27/48) Installing libarchive (3.5.1-r0)
(28/48) Installing ca-certificates (20191127-r5)
(29/48) Installing brotli-libs (1.0.9-r3)
(30/48) Installing nghttp2-libs (1.42.0-r1)
(31/48) Installing libcurl (7.74.0-r1)
(32/48) Installing ncurses-terminfo-base (6.2_p20210109-r0)
(33/48) Installing ncurses-libs (6.2_p20210109-r0)
(34/48) Installing rhash-libs (1.4.1-r0)
(35/48) Installing libuv (1.40.0-r0)
(36/48) Installing cmake (3.18.4-r1)
(37/48) Installing pcre2 (10.36-r0)
(38/48) Installing git (2.30.2-r0)
(39/48) Installing gnu-libiconv (1.15-r3)
(40/48) Installing libsodium (1.0.18-r0)
(41/48) Installing pkgconf (1.7.3-r0)
(42/48) Installing libsodium-dev (1.0.18-r0)
(43/48) Installing ncurses-dev (6.2_p20210109-r0)
(44/48) Installing openssl-dev (1.1.1j-r0)
(45/48) Installing libhistory (8.1.0-r0)
(46/48) Installing readline (8.1.0-r0)
(47/48) Installing readline-dev (8.1.0-r0)
(48/48) Installing zlib-dev (1.2.11-r3)
Executing busybox-1.32.1-r3.trigger
Executing ca-certificates-20191127-r5.trigger
OK: 261 MiB in 62 packages
Cloning into 'SoftEtherVPN'...
Updating files: 100% (1768/1768), done.
Submodule '3rdparty/BLAKE2' (https://github.com/BLAKE2/BLAKE2.git) registered for path '3rdparty/BLAKE2'
Submodule '3rdparty/tinydir' (https://github.com/cxong/tinydir.git) registered for path '3rdparty/tinydir'
Submodule 'src/Mayaqua/3rdparty/cpu_features' (https://github.com/google/cpu_features.git) registered for path 'src/Mayaqua/3rdparty/cpu_features'
Submodule 'src/libhamcore' (https://github.com/SoftEtherVPN/libhamcore.git) registered for path 'src/libhamcore'
Cloning into '/usr/src/SoftEtherVPN/3rdparty/BLAKE2'...
Cloning into '/usr/src/SoftEtherVPN/3rdparty/tinydir'...
Cloning into '/usr/src/SoftEtherVPN/src/Mayaqua/3rdparty/cpu_features'...
Cloning into '/usr/src/SoftEtherVPN/src/libhamcore'...
Submodule path '3rdparty/BLAKE2': checked out 'b52178a376ca85a8ffe50492263c2a5bc0fa4f46'
Submodule path '3rdparty/tinydir': checked out 'ec6bff2043eaac3ad25423705e63a781762a0dfd'
Submodule path 'src/Mayaqua/3rdparty/cpu_features': checked out '26133d3b620c2c27f31d571efd27371100f891e9'
Submodule path 'src/libhamcore': checked out 'b7f5d8d735b280fc77673c4a29f0436a92ca6660'
---------------------------------------------------------------------
SoftEther VPN for Unix

Copyright (c) all contributors on SoftEther VPN project in GitHub.
Copyright (c) Daiyuu Nobori, SoftEther Project at University of Tsukuba, and SoftEther Corporation.

Licensed under the Apache License, Version 2.0 (the License).

Read and understand README, LICENSE and WARNING before use.
---------------------------------------------------------------------

Welcome to the corner-cutting configure script !

'rpm' executable not found, CPack will generate DEB packages.

-- The C compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for sys/auxv.h
-- Looking for sys/auxv.h - found
-- Build date: 14/03/2021
-- Build time: 11:30:54
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.7.3")
-- Checking for one of the modules 'libsodium'
-- Found Curses: /usr/lib/libcurses.so
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.1j")
-- Found ZLIB: /lib/libz.so (found version "1.2.11")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- The CXX compiler identification is GNU 10.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Searching 16 bit integer - Using unsigned short
-- Check if the system is big endian - little endian
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/SoftEtherVPN/build

The Makefile is generated. Run 'make -C build' to build SoftEther VPN.
make: *** tmp: No such file or directory.  Stop.
The command '/bin/sh -c apk add --no-cache       binutils       build-base       readline-dev       openssl-dev       ncurses-dev       libsodium-dev       git       cmake       gnu-libiconv       zlib-dev     && git clone --recurse-submodules https://github.com/SoftEtherVPN/SoftEtherVPN.git     && cd SoftEtherVPN     && ./configure     && make -C tmp     && make -C tmp install     && tar -czf /artifacts.tar.gz /usr/local' returned a non-zero code: 2`

**Comment by Armik2** [comment]
del
